name: "Feature request ✨"
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: [needs-triage]
projects: ["hello"]
body:
  - type: textarea
    attributes:
      label: "Feature description"
      placeholder: "Describe the feature in detail"
      description: |
        Provide a detailed description of the feature, including its purpose and how it should work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Task breakdown"
      placeholder: "List the tasks required to implement this feature"
      description: |
        Provide a breakdown of the tasks required to implement this feature. For example:
        - [ ] Task 1 Initial setup and configuration
        - [ ] Task 2 Implement core functionality
        - [ ] Task 3 Write unit tests
        - [ ] Task 4 Update documentation
        - [ ] Task 5 Code review and merge
    validations:
      required: true
